### ISSUE TITLE
Asking for more details about doctor.py and patient.py

### ISSUE THREAD

**Issue by whynotkimhari** [amhkhowaja/patients-portal-for-students#2]
Hello professor @amhkhowaja ,

I see that in the testing process, we do not do anything related to doctor.py and patient.py. Can you tell more about the role of these two files, or we need to create something else to use them?

Thank you

**Comment by amhkhowaja** [comment]
More tests will be added for patients.py . You dont need to create a doctor.py implementation or related implementation to doctors . while developing it, created a doctor class to use as an attribute for assigned doctor in patients class. but its skipped for this assignment.
